// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBWiPauybJer2ONb2t_7K_3tLFgesiIkU',
    appId: '1:907610249864:web:4e79c3112c8e15124e9d3d',
    messagingSenderId: '907610249864',
    projectId: 'kidderminster-harriers-bpdeg0',
    authDomain: 'kidderminster-harriers-bpdeg0.firebaseapp.com',
    storageBucket: 'kidderminster-harriers-bpdeg0.firebasestorage.app',
    measurementId: 'G-75BZ7HBDBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59afgitRNCh3QBQYR-_VfGOPzYNAdq10',
    appId: '1:907610249864:android:8ee2be03b867ca714e9d3d',
    messagingSenderId: '907610249864',
    projectId: 'kidderminster-harriers-bpdeg0',
    storageBucket: 'kidderminster-harriers-bpdeg0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4PvO5118LF08fQgbbPJHLlW81DsSmuU',
    appId: '1:907610249864:ios:7632ab31814517c34e9d3d',
    messagingSenderId: '907610249864',
    projectId: 'kidderminster-harriers-bpdeg0',
    storageBucket: 'kidderminster-harriers-bpdeg0.firebasestorage.app',
    androidClientId: '907610249864-0l3p8gcu31f9m8195npo479d8b6ns6qn.apps.googleusercontent.com',
    iosClientId: '907610249864-7rv34n3o3584nhhv12o1gjivvs65r21a.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.touchlinetemplate',
  );
}
